### ISSUE TITLE
Importing modules that end with "in" causes indentation issues

### ISSUE THREAD

**Issue by preetpalS** [chrisbarrett/swift-mode#102]
For example, if you import the "Darwin" module, the next line gets indented incorrectly. The following indentation examples were all indented by selecting all text in the buffer and indenting everything.

Good
```Swift
import Cocoa

class Test {
}
```

Incorrect indentation
```Swift

import Cocoa
import Darwin

       class Test {
    }
```

Incorrect indentation
```Swift
import Darwin
           import Cocoa


class Test {
}
```

Workaround (use semicolon)
```Swift
import Cocoa
import Darwin;

class Test {
}
```

**Comment by ap4y** [comment]
Hey @preetpalS I checked this against latest master and it looks ok. Can you try updating the package, `melpa` has `20150818.1958`?

**Comment by preetpalS** [comment]
I am using that version of the package (and its the latest version at this time). Here is some information about my Emacs installation and the version of package I am using.

```Emacs-Lisp
(emacs-version)
                                                             
"GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.0.0, NS appkit-1343.16 Version 10.10.1 (Build 14B25))
 of 2015-01-21 on Preetpals-Air"
 
;;;; Copied from Swift-Mode package
;; Authors: Chris Barrett <chris.d.barrett@me.com>
;;       Bozhidar Batsov <bozhidar@batsov.com>
;;       Arthur Evstifeev <lod@pisem.net>
;; Version: 0.4.0-cvs
;; Package-Version: 20150818.1958
;; Package-Requires: ((emacs "24.4"))
;; Keywords: languages swift
```

I was able to reproduce the bug by starting Emacs with the --no-init flag, opening and evaluating the swift-mode.el file from the melpa package on my computer (Package-Version: 20150818.1958), and then opening and indenting a file containing all of the cases I reported in the issue.


Results of indenting the file containing all cases initially reported in the issue are below:
```Swift
import Cocoa

class Test {
}

import Cocoa
import Darwin

       class Test {
    }

import Darwin
           import Cocoa

class Test {
}

import Cocoa
import Darwin;

class Test {
}
```
Screenshots taken while trying to reproduce issue.
![screen shot of file after being indented using swift-mode](https://cloud.githubusercontent.com/assets/6419959/9430709/a1198b48-49b4-11e5-98f4-73b25f537d1c.png)
![screen shot of package version](https://cloud.githubusercontent.com/assets/6419959/9430712/a6b5e2c2-49b4-11e5-81d7-585350359451.png)

**Comment by ap4y** [comment]
Oh sorry, I missed the title of the issue :) Yep that's definitelly an issue with lexer's regex for `in` token. Seems like we are not tokenizing it, so it's a default lexer's issue. Will look into it.

**Comment by preetpalS** [comment]
No worries :), thanks for fixing this issue.
