### ISSUE TITLE
Error message when opening swift files

### ISSUE THREAD

**Issue by ckruse** [chrisbarrett/swift-mode#57]
Whenever I open a Swift file I get this error:

```
File mode specification error: (void-variable flycheck-swift-sdk-path)
```

I have to comment the `eval-after-load` block to avoid this error message and make Emacs usable again.

**Comment by ap4y** [comment]
Fix from #67 worked for me too, closing this issues since #67 was merged into master.

**Comment by mcandre** [comment]
I'm still getting `void-variable flycheck-swift-sdk-path` when I try to compile my .emacs to bytecode.

https://github.com/mcandre/dotfiles/blob/master/.emacs

**Comment by ap4y** [comment]
Yeah, I noticed that too. You can read a bit more about it [here](https://github.com/chrisbarrett/swift-mode/commit/ade8e95538f673df93b5eeb8635e3c0c40e8a1f1#commitcomment-15729379)
