### ISSUE TITLE
Incorrect indentation if a method declaration is the first item of a class declaration.

### ISSUE THREAD

**Issue by melton1968** [chrisbarrett/swift-mode#73]
The indentation is correct with the `var xyz`
    
    class Foo {
        var xyz
        func Bar {
            let x = 1
            let y = 2
        }
    }

However, the indication is incorrect if the `func Foo` method is the first element of the class.

    class Foo {
        func Bar {
        let x = 1
        let y = 2
    }
    }

Experimentation seems to indicate that a method definition immediately following an opening brace produces incorrect results.

    func g() {
        func x() {
        let x = 1
    }
    }

I tried to decipher the issue, but wasn't able to make much progress without at least a few pointers in the right direction.

**Comment by ap4y** [comment]
fixed in #76.
