### ISSUE TITLE
Defining indention levels

### ISSUE THREAD

**Issue by roxlu** [chrisbarrett/swift-mode#77]
Hi Chris, sorry to contact you through an issue, but I can't find your contact info. 

I was wondering if there is a way to set the idention levels because currently my code
jumps outside the view of my editors.  I've pasted a snippet of my code which shows
the indention that I want to change: 

https://gist.githubusercontent.com/roxlu/8498420d0b5524675e3c/raw/27a18777e5adabc76c5eaf2cb0bc658f08e65c07/ViewController.swift

Thanks for this awesome swift-mode!

**Comment by ap4y** [comment]
Hey @roxlu, unfortunately this behavior for blocks doesn't work well at the moment. There is ongoing discussion in #75. Some issues already fixed in #76, once it will be merged, this issue will hopefully gone.

**Comment by roxlu** [comment]
Hey @ap4y awesome! Can't wait ^.^

**Comment by ap4y** [comment]
fixed in #76.
