### ISSUE TITLE
Indentation Issue: body of bare (no override) function in a class doesn't indent 

### ISSUE THREAD

**Issue by dougbeal** [chrisbarrett/swift-mode#81]
If there is a keyword such as override, it idents correctly

**Comment by ap4y** [comment]
hi @dougbeal, thanks for reporting. I'm pretty sure it's fixed in #76 already. I will double check it before merging it.

**Comment by dougbeal** [comment]
Sweet.  Let me merge in your changes and see if it passes my test.

**Comment by ap4y** [comment]
fixed in #76.
