### ISSUE TITLE
Can't load CoreGraphics

### ISSUE THREAD

**Issue by mmb90** [chrisbarrett/swift-mode#93]
I've installed swift-mode as instructed and I've already been using flycheck for other languages. I added `(add-to-list 'flycheck-checkers 'swift)` also and the checker tries to run. I get this error,
`Suspicious state from syntax checker swift: Checker swift returned non-zero exit code 1, but no errors from output: <unknown>:0: error: cannot load underlying module for 'CoreGraphics
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun -sdk macosx swift" to select the default OS X SDK installed with Xcode`
I've googled around but the issue, as far as I can tell, is usually related to making scripts in swift and running them from the terminal with a solution of exporting SDKROOT in the .bash_profile. Any clues?

**Comment by ap4y** [comment]
Hi @mmb90, `flycheck` checker uses plain `swift` frontend, which doesn't know about platform specific modules unless `-sdk` is specified. You can set `sdk` variable for the flycheck via [this](https://github.com/chrisbarrett/swift-mode/blob/master/swift-mode.el#L617) variable.

**Comment by mmb90** [comment]
I'm afraid I'm still confused, how can I set this variable? Forgive my naivety.

**Comment by nicklanasa** [comment]
@mmb90 I was getting the same error until I added the following to my `init.el`

```
(setq flycheck-swift-sdk-path "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk/")
```

If you don't know your SDK path, you can find it by running this command in terminal:

```
xcrun --show-sdk-path
```

**Comment by mmb90** [comment]
Awesome, I fixed it with this. Thanks!

```elisp
(defvar flycheck-swift-sdk-path)
(setq flycheck-swift-sdk-path "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk")
```
